name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Realizando testes unit치rios
        run: echo "Testes sendo executados"
      - name: Validando c칩digo
        run: echo "IA est치 validando o c칩digo"
      - name: Realizando deploy
        run: echo "Realizando deploy"